### ISSUE TITLE
setjsonconfigconnectionstring Task does not fail on internal exception

### ISSUE THREAD

**Issue by giuliov** [benday/build-utilities#1]
Hi Ben,
I passed a wrong filename to *setjsonconfigconnectionstring* and the task reported success where failure was expected. Here an extract from log
```
Version 1.0.1
System.IO.FileNotFoundException: File for argument 'filename' was not found.
File name: 'D:\agents\03\_work\r3\a\$ArtifactLink)\ConfigFiles\ApiLayer.HttpService\appsettings.json'
    at Benday.BuildUtilities.Core.ConsoleUi.CommandBase.AssertFileExists(String path, String argumentName)
    at Benday.BuildUtilities.Core.ConsoleUi.SetJsonValueCommand.AfterValidateArguments()
    at Benday.BuildUtilities.Core.ConsoleUi.CommandBase..ctor(String[] args)
    at Benday.BuildUtilities.Core.ConsoleUi.SetJsonValueCommand..ctor(String[] args)
    at Benday.BuildUtilities.Core.ConsoleUi.Program.Main(String[] args)
Completed with return code 0
```

**Comment by benday** [comment]
@giuliov -- I just noticed that you submitted this issue today.  (5 months later.  oops.)  I think that this has already been fixed.  Please let me know if this issue is still happening.
